config/routes.rb
Rails.application.routes.draw do
  resources :options
  root "options#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
class Option < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: %i[ show edit update destroy ]

  # GET /options or /options.json
  def index
    @options = Option.all
  end

  # GET /options/1 or /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options or /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: "Option was successfully created." }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1 or /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: "Option was successfully updated." }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1 or /options/1.json
  def destroy
    @option.destroy!

    respond_to do |format|
      format.html { redirect_to options_path, status: :see_other, notice: "Option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def option_params
      params.require(:option).permit(:stock_price, :strike_price, :expiry_date, :risk_free_rate, :volatility, :option_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Option Valuator" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/options/_form.html.erb
<%= form_with(model: option) do |form| %>
  <% if option.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
        <% option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stock_price, style: "display: block" %>
    <%= form.text_field :stock_price %>
  </div>

  <div>
    <%= form.label :strike_price, style: "display: block" %>
    <%= form.text_field :strike_price %>
  </div>

  <div>
    <%= form.label :expiry_date, style: "display: block" %>
    <%= form.date_field :expiry_date %>
  </div>

  <div>
    <%= form.label :risk_free_rate, style: "display: block" %>
    <%= form.text_field :risk_free_rate %>
  </div>

  <div>
    <%= form.label :volatility, style: "display: block" %>
    <%= form.text_field :volatility %>
  </div>

  <div>
    <%= form.label :option_type, style: "display: block" %>
    <%= form.text_field :option_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/options/_option.html.erb
<div id="<%= dom_id option %>">
  <p>
    <strong>Stock price:</strong>
    <%= option.stock_price %>
  </p>

  <p>
    <strong>Strike price:</strong>
    <%= option.strike_price %>
  </p>

  <p>
    <strong>Expiry date:</strong>
    <%= option.expiry_date %>
  </p>

  <p>
    <strong>Risk free rate:</strong>
    <%= option.risk_free_rate %>
  </p>

  <p>
    <strong>Volatility:</strong>
    <%= option.volatility %>
  </p>

  <p>
    <strong>Option type:</strong>
    <%= option.option_type %>
  </p>

</div>

app/views/options/edit.html.erb
<% content_for :title, "Editing option" %>

<h1>Editing option</h1>

<%= render "form", option: @option %>

<br>

<div>
  <%= link_to "Show this option", @option %> |
  <%= link_to "Back to options", options_path %>
</div>

app/views/options/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Options" %>

<h1>Options</h1>

<div id="options">
  <% @options.each do |option| %>
    <%= render option %>
    <p>
      <%= link_to "Show this option", option %>
    </p>
  <% end %>
</div>

<%= link_to "New option", new_option_path %>

app/views/options/new.html.erb
<% content_for :title, "New option" %>

<h1>New option</h1>

<%= render "form", option: @option %>

<br>

<div>
  <%= link_to "Back to options", options_path %>
</div>

app/views/options/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @option %>

<div>
  <%= link_to "Edit this option", edit_option_path(@option) %> |
  <%= link_to "Back to options", options_path %>

  <%= button_to "Destroy this option", @option, method: :delete %>
</div>